### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by bluetechsky** [OrbitalMan/EpubGenApp#2]
Dear Stanislav Shemiakov,
I saw your PR
https://github.com/FolioReader/FolioReaderKit/pull/388

Your effort is awesome!
I'd like to ask could you please run on iOS 14?

I cannot run Example code on iOS 14 because of issue calling js functions

Thanks alot!
Hung

**Comment by bluetechsky** [comment]
@OrbitalMan 

Dear Stanislav Shemiakov,
I saw your PR
FolioReader/FolioReaderKit#388

Your effort is awesome!
I'd like to ask could you please run on iOS 14?

I cannot run Example code on iOS 14 because of issue calling js functions

Thanks alot!
Hung

**Comment by OrbitalMan** [comment]
@bluetechsky Hello, this project is pretty much abandoned for quite a long time - I had a lot of issues with JS functions too, and I don't have much experience with JS, so I don't think I can help with that, sorry...

**Comment by bluetechsky** [comment]
@OrbitalMan Thank you very much for your reply!
I believe you could build successfully in the past iOS version.
Do you remember what is your last success build iOS version?
I would like to try to run in that version.
Thank you very much again.
Hung

**Comment by OrbitalMan** [comment]
@bluetechsky uuuuhh umm, I guess iOS 12-ish? It was a couple years ago...

**Comment by bluetechsky** [comment]
@OrbitalMan okeiy, thank you very much for your information. I will take some time to dig into it. Thanks again for your time!

**Comment by OrbitalMan** [comment]
No problem! Good luck with this!

**Comment by amrangry** [comment]
@bluetechsky did you able to figure out the solution 
i found a solution for this issue but not pretty sure if its the right one or not,
let me know if you are still interested to discuss more regarding

**Comment by AravindSripathi** [comment]
Hello, sorry if this is late. Recently downloaded @OrbitalMan build and integrated it as a local library in pod file.

Tested in iOS 15.5

As it was mentioned the javascript functions were not working which lead to the UI not working.

Checked through the original code and found that the JS file and CSS file used for the UI were not inserted into the HTML.

Here is the working solution. Check for FolioReaderCenter.swift file and add this code below   "//Insert viewport" comment

        let mediaOverlayStyleColors = "\"\(self.readerConfig.mediaOverlayColor.hexString(false))\", \"\(self.readerConfig.mediaOverlayColor.highlightColor().hexString(false))\""

        // Inject CSS 
         let jsFilePath = Bundle.frameworkBundle().path(forResource: "Bridge", ofType: "js") 
         let cssFilePath = Bundle.frameworkBundle().path(forResource: "Style", ofType: "css") 
         let cssTag = "<link rel=\"stylesheet\" type=\"text/css\" href=\"\(cssFilePath!)\">" 
         let jsTag = "<script type=\"text/javascript\" src=\"\(jsFilePath!)\"></script>" + 
         "<script type=\"text/javascript\">setMediaOverlayStyleColors(\(mediaOverlayStyleColors))</script>" 
  
         let toInject = "\n\(cssTag)\n\(jsTag)\n</head>"

This will solve your problem.
